// Code generated by options-gen v0.55.3. DO NOT EDIT.

package ainvoke

import (
	fmt461e464ebed9 "fmt"
	"io"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptRunOptionsSetter func(o *RunOptions)

func NewRunOptions(
	options ...OptRunOptionsSetter,
) RunOptions {
	var o RunOptions

	// Setting defaults from func
	defaultOpts := defaultRunOptions()
	o.stdout = defaultOpts.stdout
	o.stderr = defaultOpts.stderr
	o.tty = defaultOpts.tty

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithStdout(opt io.Writer) OptRunOptionsSetter {
	return func(o *RunOptions) { o.stdout = opt }
}

func WithStderr(opt io.Writer) OptRunOptionsSetter {
	return func(o *RunOptions) { o.stderr = opt }
}

func WithTty(opt bool) OptRunOptionsSetter {
	return func(o *RunOptions) { o.tty = opt }
}

func (o *RunOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("stdout", _validate_RunOptions_stdout(o)))
	errs.Add(errors461e464ebed9.NewValidationError("stderr", _validate_RunOptions_stderr(o)))
	return errs.AsError()
}

func _validate_RunOptions_stdout(o *RunOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.stdout, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `stdout` did not pass the test: %w", err)
	}
	return nil
}

func _validate_RunOptions_stderr(o *RunOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.stderr, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `stderr` did not pass the test: %w", err)
	}
	return nil
}
