version: '3'

vars:
  GOLANGCI_LINT_VERSION: v2.8.0

env:
  CGO_ENABLED: 0

tasks:
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --timeout 5m

  lint:install:
    desc: Install golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}

  test:
    desc: Run tests
    cmds:
      - go test ./...
