// Code generated by options-gen v0.55.3. DO NOT EDIT.

package adk

import (
	fmt461e464ebed9 "fmt"
	"time"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptExecAgentOptionsSetter func(o *ExecAgentOptions)

func NewExecAgentOptions(
	name string,
	description string,
	cmd []string,
	options ...OptExecAgentOptionsSetter,
) ExecAgentOptions {
	var o ExecAgentOptions

	// Setting defaults from func
	defaultOpts := defaultExecAgentOptions()
	o.name = defaultOpts.name
	o.description = defaultOpts.description
	o.prompt = defaultOpts.prompt
	o.cmd = defaultOpts.cmd
	o.extraArgs = defaultOpts.extraArgs
	o.useTTY = defaultOpts.useTTY
	o.timeout = defaultOpts.timeout
	o.inputSchema = defaultOpts.inputSchema
	o.outputSchema = defaultOpts.outputSchema
	o.runDir = defaultOpts.runDir

	o.name = name
	o.description = description
	o.cmd = cmd

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithExecAgentPrompt(opt string) OptExecAgentOptionsSetter {
	return func(o *ExecAgentOptions) { o.prompt = opt }
}

func WithExecAgentExtraArgs(opt ...string) OptExecAgentOptionsSetter {
	return func(o *ExecAgentOptions) { o.extraArgs = append(o.extraArgs, opt...) }
}

func WithExecAgentUseTTY(opt bool) OptExecAgentOptionsSetter {
	return func(o *ExecAgentOptions) { o.useTTY = opt }
}

func WithExecAgentTimeout(opt time.Duration) OptExecAgentOptionsSetter {
	return func(o *ExecAgentOptions) { o.timeout = opt }
}

func WithExecAgentInputSchema(opt string) OptExecAgentOptionsSetter {
	return func(o *ExecAgentOptions) { o.inputSchema = opt }
}

func WithExecAgentOutputSchema(opt string) OptExecAgentOptionsSetter {
	return func(o *ExecAgentOptions) { o.outputSchema = opt }
}

func WithExecAgentRunDir(opt string) OptExecAgentOptionsSetter {
	return func(o *ExecAgentOptions) { o.runDir = opt }
}

func (o *ExecAgentOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("name", _validate_ExecAgentOptions_name(o)))
	errs.Add(errors461e464ebed9.NewValidationError("description", _validate_ExecAgentOptions_description(o)))
	errs.Add(errors461e464ebed9.NewValidationError("cmd", _validate_ExecAgentOptions_cmd(o)))
	return errs.AsError()
}

func _validate_ExecAgentOptions_name(o *ExecAgentOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.name, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `name` did not pass the test: %w", err)
	}
	return nil
}

func _validate_ExecAgentOptions_description(o *ExecAgentOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.description, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `description` did not pass the test: %w", err)
	}
	return nil
}

func _validate_ExecAgentOptions_cmd(o *ExecAgentOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.cmd, "required,dive,required"); err != nil {
		return fmt461e464ebed9.Errorf("field `cmd` did not pass the test: %w", err)
	}
	return nil
}
